### ISSUE TITLE
Add WGSL-Toy link in Demos

### ISSUE THREAD

**Issue by HypnosNova** [mikbry/awesome-webgpu#7]
https://github.com/ValeeraJS/WGSL-Toy

I make this repository. Just like shadertoy, people could write WGSL or GLSL ES4.5 and use webgpu to render their shaders.
I think this is a great tool for developers to learn webgpu shader programming.

Thanks.

**Comment by mikbry** [comment]
Thanks @HypnosNova, great tool ! I added the link to demos section
